project_id = "qzqucuiwgdilgramnizm"

[functions.send-calendar-invite]
verify_jwt = true

[functions.check-ip]
verify_jwt = false

[functions.check-in]
verify_jwt = false

[functions.send-daily-credits-report]
verify_jwt = false

[functions.send-credit-email]
verify_jwt = false

[functions.send-test-email]
verify_jwt = false

[functions.send-admin-notification-test]
verify_jwt = false
